[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking = "81ynpt6yn1PEpJXESPW2noQn6hKdU9VPvTXfxg6wzKCG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
